add_newline = false

format = """
$username$hostname$directory$git_branch
$cmd_duration$character"""

[character]
success_symbol = "[ >](bold green)"
error_symbol = "[ x](bold red)"

[package]
disabled = true

[git_branch]
style = "bg:#7e9cd8 fg:black"
symbol = " "
truncation_length = 10
format = "[](bold fg:#7e9cd8)[$symbol$branch(:$remote_branch) ](fg:black bg:#7e9cd8)[](bold fg:#7e9cd8)"

[git_status]
conflicted = " ⚡"
ahead = " ↑"
behind = " ↓"
diverged = " ↕"
untracked = " ?"
stashed = " ⚑"
modified = " !"
staged = "[+$count](green)"
renamed = " →"
deleted = " ✘"

[hostname]
ssh_only = false
format = "[@$hostname](bg:#957fb8 fg:black)[ ](bold fg:#957fb8)"
disabled = false

[username]
style_user = "bg:#957fb8 fg:black"
style_root = "bg:red fg:white"
format = "[](bold fg:#957fb8)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " ~"
read_only = " "
style = "bg:#98bb6c fg:black"
truncation_length = 5
format = "[](bold fg:#98bb6c)[ $path ]($style)[](bold fg:#98bb6c)"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[cmd_duration]
min_time = 5000
format = "[](bold fg:#ffa066)[ $duration ](bg:#ffa066 fg:black)[](bold fg:#ffa066)"

[memory_usage]
disabled = true

[time]
disabled = true
