[window]
padding.x = 25
padding.y = 25
decorations = "None"
blur = true
dynamic_padding = false

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"
bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"
size = 8

[font.offset]
x = 0
y = 1

[colors.primary]
background = "#1a1a1a"
foreground = "#ffffff"

[colors.cursor]
text = "#0a0a0a"
cursor = "#ffffff"

[colors.normal]
black = "#1a1a1a"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[cursor]
style.shape = "Block"
style.blinking = "On"
blink_interval = 750
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/fish"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[terminal]
